name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/flyio-deploy@v3.12.13 # This is the action
        with:
          flyio_api_key: ${{ secrets.flyio_API_KEY }}
          flyio_app_name: ${{ secrets.flyio_APP_NAME }}
          flyio_email: ${{ secrets.flyio_EMAIL }}
